// LOADING LIBRARIES
const express = require('@feathersjs/express');

// CREATING AN EXPRESS SERVER
// EXPRESS IS A LIBRARY THAT HELPS IN CREATING SERVER APPLICATIONS IN THE NODEJS PLATFORM
// NODEJS IS JUST PLATFORM/RUNTIME TO RUN JAVASCRIPT OUTSIDE OF THE BROWSER
const app = express();

//MIDDLEWARE ARE SERVICES THAT HAPPENS IN THE MIDDLE OF REQUEST AND EXECUTION OF MAIN TASKS
app.use(express.static(__dirname)); // SERVING OF STATIC/FRONTEND FILES

// PREVENTS THE SCRIPT FROM EXITTING BY LETTING IT LISTEN ON A SPECIFIC PORT
// RUNNING A NODE APPLICATION REQUIRES TYPING THE COMMAND "node app.js" LIKE PYTHON "python main.py"
app.listen(3030).on('listening', () => {
	console.log('Feathers server running on localhost:3030');
});
